PACKAGE_NAME="hid-honeycomb-bravo"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="hid-honeycomb-bravo"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make KVER=${kernelver} KDIR=${kernel_source_dir}"
CLEAN="make KVER=${kernelver} KDIR=${kernel_source_dir} clean"
AUTOINSTALL="yes"
